# Generated by Django 4.2.5 on 2023-11-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0003_rename_holaa_databasehumidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.CharField(max_length=30)),
                ('data_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataBasePhosphorus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.CharField(max_length=30)),
                ('data_value', models.IntegerField()),
            ],
        ),
    ]
